(() => {
'use strict';
const STORE = 'ders-rutin-tracker-v3';
const COLORS = ['#346def','#7a68ef','#17aeaa','#f29e4c','#e56e98','#6b9b46','#a46de1','#178aba'];
const DAY_NAMES = ['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'];
const WEEKDAYS_SHORT = ['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'];
const fmt = new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'long',year:'numeric'});
const $ = q => document.querySelector(q);
const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad = n => String(n).padStart(2,'0');
const dateKey = d => `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parseDate = key => { const parts=String(key).split('-').map(Number);const d=new Date(parts[0],parts[1]-1,parts[2],12);return Number.isNaN(d.getTime())?new Date():d; };
const moveDay = (key,n) => {let d=parseDate(key);d.setDate(d.getDate()+n);return dateKey(d);};
const nowKey = () => dateKey(new Date());
const monday = key => {let d=parseDate(key);d.setDate(d.getDate()-(d.getDay()+6)%7);return dateKey(d);};
const within = (date,from,to) => date>=from && date<to;
const id = () => Math.random().toString(36).slice(2,11)+Date.now().toString(36);
const minLabel = min => Number.isInteger(min/60)?`${min/60} sa`:`${(min/60).toLocaleString('tr-TR',{maximumFractionDigits:2})} sa`;
const hrLabel = sec => (sec/3600).toLocaleString('tr-TR',{minimumFractionDigits:1,maximumFractionDigits:1});
const prettyTime = sec => { sec=Math.max(0,Math.floor(sec));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return `${pad(h)}:${pad(m)}:${pad(s)}`; };
const pct = (v,total) => total>0?Math.min(100,Math.round(v/total*100)):0;
const safeColor = (str,i=0) => /^#[0-9a-fA-F]{6}$/.test(str)?str:COLORS[i%COLORS.length];
const safeId = (x) => /^[a-zA-Z0-9_-]{1,80}$/.test(x||'')?x:id();
function defaults(){return {version:3,courses:[
 {id:'termo',name:'Termodinamik',weeklyGoal:240,color:COLORS[0]},
 {id:'makina',name:'Makina Elemanları',weeklyGoal:150,color:COLORS[1]},
 {id:'lineer',name:'Lineer Cebir',weeklyGoal:120,color:COLORS[2]},
 {id:'diger',name:'Diğer dersler (özelleştir)',weeklyGoal:390,color:COLORS[3]}
],habits:[{id:'h_su',name:'Yeterli su iç',emoji:'💧'},{id:'h_hareket',name:'Hareket et',emoji:'🚶'},{id:'h_okuma',name:'Kitap oku',emoji:'📖'},{id:'h_ing',name:'İngilizce tekrar',emoji:'🗣️'}],tasks:[],habitChecks:{},notes:{},sessions:[],schedule:[],timer:{courseId:'termo',elapsedSec:0,startedAt:null,running:false}};}
function cleanData(raw, resumeTimer=false){
 const base=defaults();if(!raw||typeof raw!=='object'||Array.isArray(raw))return base;
 const arr=(v,n)=>Array.isArray(v)?v.slice(0,n):[];
 const str=(v,n=120)=>typeof v==='string'?v.slice(0,n):'';
 const courses=arr(raw.courses,60).map((c,i)=>({id:safeId(c?.id),name:str(c?.name,75)||`Ders ${i+1}`,weeklyGoal:Math.max(0,Math.min(6000,Math.round(Number(c?.weeklyGoal)||0))),color:safeColor(c?.color,i)}));
 if(courses.length)base.courses=courses;
 const cid=new Set(base.courses.map(c=>c.id));
 const habits=arr(raw.habits,100).map(h=>({id:safeId(h?.id),name:str(h?.name,85)||'Alışkanlık',emoji:str(h?.emoji,8)||'✓'}));
 if(Array.isArray(raw.habits))base.habits=habits;
 const hid=new Set(base.habits.map(h=>h.id));
 base.tasks=arr(raw.tasks,5000).filter(t=>/^\d{4}-\d{2}-\d{2}$/.test(t?.due||'')).map(t=>({id:safeId(t.id),text:str(t.text,450),due:t.due,courseId:cid.has(t.courseId)?t.courseId:'',done:!!t.done})).filter(t=>t.text);
 base.sessions=arr(raw.sessions,30000).filter(s=>typeof s?.at==='string'&&!Number.isNaN(Date.parse(s.at))&&cid.has(s.courseId)&&Number.isFinite(Number(s.seconds))&&Number(s.seconds)>0).map(s=>({id:safeId(s.id),courseId:s.courseId,seconds:Math.min(86400,Math.floor(Number(s.seconds))),at:s.at}));
 if(raw.habitChecks&&typeof raw.habitChecks==='object'&&!Array.isArray(raw.habitChecks)){
  for(const [day,checks] of Object.entries(raw.habitChecks).slice(0,2500))if(/^\d{4}-\d{2}-\d{2}$/.test(day))base.habitChecks[day]=arr(checks,100).filter(h=>hid.has(h));
 }
 if(raw.notes&&typeof raw.notes==='object'&&!Array.isArray(raw.notes)){
  for(const [day,note] of Object.entries(raw.notes).slice(0,2500))if(/^\d{4}-\d{2}-\d{2}$/.test(day))base.notes[day]=str(note,10000);
 }
 base.schedule=arr(raw.schedule,1000).filter(s=>Number.isInteger(Number(s?.day))&&Number(s.day)>=0&&Number(s.day)<=6&&/^\d{2}:\d{2}$/.test(s.start||'')&&/^\d{2}:\d{2}$/.test(s.end||'')&&s.start<s.end).map(s=>({id:safeId(s.id),day:Number(s.day),start:s.start,end:s.end,title:str(s.title,110)||'Ders',kind:s.kind==='study'?'study':'class'}));
 // Imported timers do not resume automatically; they stay paused to avoid accidental time accrual.
 const t=raw.timer||{};const ts=Number(t.startedAt);const shouldResume=resumeTimer&&t.running&&Number.isFinite(ts)&&ts>0&&ts<=Date.now()&&ts>Date.now()-7*86400000;
 base.timer={courseId:cid.has(t.courseId)?t.courseId:base.courses[0].id,elapsedSec:Math.max(0,Math.min(86400,Math.floor(Number(t.elapsedSec)||0))),startedAt:shouldResume?ts:null,running:!!shouldResume};
 return base;
}
function load(){try{const value=localStorage.getItem(STORE);return value?cleanData(JSON.parse(value),true):defaults();}catch(e){return defaults();}}
let state=load(), tab=location.hash.replace('#','')||'anasayfa', chosenDay=nowKey(), noteSaveTimeout=null, toastTimeout=null;
if(!['anasayfa','plan','istatistik','ayarlar'].includes(tab))tab='anasayfa';
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));$('#syncStatus').textContent='● Bu cihazda kayıtlı';}catch(e){$('#syncStatus').textContent='● Kayıt alanı dolu';toast('Kayıt yapılamadı. Ayarlardan yedek alıp alan açın.');}}
function toast(s){const node=$('#toast');node.textContent=s;node.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>node.classList.remove('show'),3000);}
function courseFor(cid){return state.courses.find(c=>c.id===cid);}
function sessionDay(s){return dateKey(new Date(s.at));}
function sumSec(from,to,cid){return state.sessions.reduce((n,s)=>n+((!cid||s.courseId===cid)&&within(sessionDay(s),from,to)?s.seconds:0),0);}
function weekStats(date){const start=monday(date),end=moveDay(start,7);return {start,end,seconds:sumSec(start,end),goal:state.courses.reduce((n,c)=>n+c.weeklyGoal*60,0),sessions:state.sessions.filter(s=>within(sessionDay(s),start,end)).length};}
function habitDone(day,hid){return (state.habitChecks[day]||[]).includes(hid);}
function habitStreak(hid){let n=0,day=nowKey();if(!habitDone(day,hid))day=moveDay(day,-1);while(n<2000&&habitDone(day,hid)){n++;day=moveDay(day,-1);}return n;}
function timerElapsed(){let t=state.timer;return t.elapsedSec+(t.running&&t.startedAt?Math.max(0,Math.floor((Date.now()-t.startedAt)/1000)):0);}
function coursesOptions(chosen='',includeNone=false){return `${includeNone?'<option value="">Ders seçme</option>':''}`+state.courses.map(c=>`<option value="${esc(c.id)}" ${c.id===chosen?'selected':''}>${esc(c.name)}</option>`).join('');}
function sectionHead(title,sub='',action=''){return `<div class="card-head"><div><h2>${title}</h2>${sub?`<p class="section-detail">${sub}</p>`:''}</div>${action}</div>`;}
function courseBars(start,end){return `<div class="course-progress">${state.courses.map(c=>{const actual=sumSec(start,end,c.id),goal=c.weeklyGoal*60;return `<div class="course-row"><div class="course-title-line"><span><i class="course-dot" style="background:${c.color}"></i>${esc(c.name)}</span><span class="count">${hrLabel(actual)} / ${minLabel(c.weeklyGoal)}</span></div><div class="course-meter"><span style="width:${pct(actual,goal)}%;background:${c.color}"></span></div></div>`;}).join('')}</div>`;}
function dateNavigation(){return `<div class="date-controls"><button type="button" class="nav-date" data-action="prev-day" aria-label="Önceki gün">‹</button><div class="date-pill"><input aria-label="Seçili tarih" id="chosenDate" type="date" value="${chosenDay}"></div><button type="button" class="nav-date" data-action="next-day" aria-label="Sonraki gün">›</button></div>`;}
function pageIntro(kicker,title,desc,allowDate=false){return `<div class="head-row"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p class="subtle">${desc}</p></div>${allowDate?dateNavigation():''}</div>`;}
function taskList(date){const list=state.tasks.filter(t=>t.due===date).sort((a,b)=>Number(a.done)-Number(b.done));return list.length?list.map(t=>`<div class="task-row ${t.done?'done':''}"><input class="round-check" data-task-check="${esc(t.id)}" type="checkbox" ${t.done?'checked':''} aria-label="${esc(t.text)} tamamlandı"><div class="task-text">${esc(t.text)} ${t.courseId&&courseFor(t.courseId)?`<span class="tag">${esc(courseFor(t.courseId).name)}</span>`:''}</div><button type="button" class="mini-remove" data-action="delete-task" data-id="${esc(t.id)}" title="Görevi sil" aria-label="Görevi sil">×</button></div>`).join(''):`<div class="empty"><span class="empty-icon">☑</span>Bu güne henüz görev eklenmedi.</div>`;}
function habitsList(date){return state.habits.length?`<div class="habit-list">${state.habits.map(h=>`<div class="habit-row"><span class="habit-emoji">${esc(h.emoji)}</span><div class="habit-name">${esc(h.name)}<div class="habit-streak">${habitStreak(h.id)?`🔥 ${habitStreak(h.id)} gün seri`:'Her gün yeni bir fırsat'}</div></div><button type="button" class="habit-toggle ${habitDone(date,h.id)?'checked':''}" data-action="toggle-habit" data-id="${esc(h.id)}" aria-label="${esc(h.name)} ${habitDone(date,h.id)?'işaretini kaldır':'tamamlandı olarak işaretle'}">✓</button></div>`).join('')}</div>`:`<div class="empty">Ayarlar'dan ilk alışkanlığını ekle.</div>`;}
function focusWidget(){return `<div class="card">${sectionHead('Odak Sayacı','Arka planda geçen zaman da sayılır.')}<div class="focus-body"><div class="timer-label">Çalışma süren</div><div class="timer-value" id="runningTimer">${prettyTime(timerElapsed())}</div><p class="timer-hint" id="timerMode">${state.timer.running?'Şu anda çalışıyorsun':'Hazır olduğunda başlat'}</p><label class="field-label" for="timerCourse">Çalıştığın ders</label><select id="timerCourse" class="field" ${state.timer.running?'disabled':''}>${coursesOptions(state.timer.courseId)}</select><div class="gap-14"></div><div class="focus-actions"><button type="button" class="button ${state.timer.running?'secondary':'primary'}" data-action="${state.timer.running?'pause-timer':'start-timer'}">${state.timer.running?'Ⅱ Duraklat':'▶ Başlat'}</button><button type="button" class="button light" data-action="finish-timer" ${timerElapsed()<1?'disabled':''}>✓ Kaydet</button></div><div class="focus-note">Kaydet tuşu süreyi ilgili dersin istatistiğine ekler.</div></div><div class="gap-14"></div><button type="button" class="button light full" data-action="open-manual">＋ Manuel çalışma süresi ekle</button></div>`;}
function renderHome(){const w=weekStats(chosenDay),done=state.tasks.filter(t=>t.due===chosenDay&&t.done).length,taskNum=state.tasks.filter(t=>t.due===chosenDay).length,habits=state.habits.filter(h=>habitDone(chosenDay,h.id)).length,weekPct=pct(w.seconds,w.goal);return `${pageIntro('GÜNLÜK ÇALIŞMA ALANI','İlerlemenin her günü değerli.','Görevlerini planla, alışkanlıklarını sürdür ve çalışma süreni takip et.',true)}
 <div class="metric-grid">
  <div class="metric-card"><div class="metric-top">Haftalık Çalışma <span class="metric-icon">◷</span></div><div><span class="metric-value">${hrLabel(w.seconds)}</span><span class="metric-suffix">saat</span></div><div class="meter"><span style="width:${weekPct}%"></span></div><div class="metric-help">Hedef ${hrLabel(w.goal)} saat · %${weekPct}</div></div>
  <div class="metric-card"><div class="metric-top">Bugünkü Görevler <span class="metric-icon">✓</span></div><div><span class="metric-value">${done}</span><span class="metric-suffix">/ ${taskNum}</span></div><div class="meter green"><span style="width:${pct(done,taskNum)}%"></span></div><div class="metric-help">Tamamlanan görevler</div></div>
  <div class="metric-card"><div class="metric-top">Alışkanlıklar <span class="metric-icon">✦</span></div><div><span class="metric-value">${habits}</span><span class="metric-suffix">/ ${state.habits.length}</span></div><div class="meter amber"><span style="width:${pct(habits,state.habits.length)}%"></span></div><div class="metric-help">Seçili günün rutini</div></div>
  <div class="metric-card"><div class="metric-top">Odak Oturumları <span class="metric-icon">▤</span></div><div><span class="metric-value">${w.sessions}</span></div><div class="meter"><span style="width:${Math.min(100,w.sessions*10)}%"></span></div><div class="metric-help">Bu haftaki kayıt sayısı</div></div>
 </div>
 <div class="columns"><div class="stack"><section class="card">${sectionHead('Günlük Görevler',esc(fmt.format(parseDate(chosenDay))),`<button type="button" class="text-action" data-action="go-plan">Haftalık plan →</button>`)}<form id="addTaskForm" class="task-form"><input class="field" name="taskText" maxlength="450" autocomplete="off" aria-label="Görev adı" placeholder="Yeni bir görev yaz..." required><select name="taskCourse" class="field" style="width:135px" aria-label="İlgili ders">${coursesOptions('',true)}</select><button class="button primary" type="submit">＋ Ekle</button></form><div class="task-list">${taskList(chosenDay)}</div></section>
  <section class="card">${sectionHead('Ders Bazlı İlerleme','Bu haftanın gerçek çalışma süreleri',`<button type="button" class="text-action" data-action="go-stats">Detaylar →</button>`)}${courseBars(w.start,w.end)}<div class="divider"></div><div class="hint">Ders tamamlama işareti süre eklemez. Yalnızca odak sayacı veya manuel kayıtlar bu grafikleri etkiler.</div></section>
  <section class="card">${sectionHead('Günlük Notlar','Kendine küçük bir not bırak')}<textarea id="dailyNote" class="field textarea" aria-label="Günlük not" placeholder="Bugün neler öğrendin, yarın neye odaklanacaksın?" maxlength="10000">${esc(state.notes[chosenDay]||'')}</textarea><div class="notes-status" id="noteStatus">Otomatik kaydedilir.</div></section>
 </div><div class="stack">${focusWidget()}<section class="card">${sectionHead('Günlük Alışkanlıklar',esc(fmt.format(parseDate(chosenDay))),`<button type="button" class="text-action" data-action="go-settings">Düzenle →</button>`)}${habitsList(chosenDay)}</section><section class="highlight-card"><div class="eyebrow" style="color:#cddcff">BU HAFTANIN HEDEFİ</div><h2>${hrLabel(w.goal)} saatlik ilerleme</h2><p class="subtle">Haftalık hedefinin %${weekPct} kadarını tamamladın.</p><div class="progress-white"><span style="width:${weekPct}%"></span></div><div class="inline-row" style="justify-content:space-between"><small>${hrLabel(w.seconds)} / ${hrLabel(w.goal)} saat</small><button class="button small" type="button" data-action="go-plan">Planı gör ↗</button></div></section></div></div>`;}
function scheduleItem(s){return `<div class="schedule-item"><span><time>${s.start}–${s.end}</time> &nbsp; ${esc(s.title)} <em>(${s.kind==='class'?'Okul / ders':'Planlanan etüt'})</em></span><button class="mini-remove" type="button" data-action="delete-schedule" data-id="${esc(s.id)}" title="Programdan çıkar">×</button></div>`;}
function renderPlan(){const start=monday(chosenDay),end=moveDay(start,7);const week=weekStats(chosenDay);return `${pageIntro('HAFTALIK PLAN','Günlerini planla.','Okul saatleri çalışma süresine dahil edilmez; gerçek süreyi odak sayacında kaydet.',true)}
 <div class="columns"><div class="stack"><section class="card">${sectionHead('Bu Haftanın Günleri',`${fmt.format(parseDate(start))} – ${fmt.format(parseDate(moveDay(end,-1)))}`)}<div class="day-grid">${Array.from({length:7},(_,i)=>{const d=moveDay(start,i),sec=sumSec(d,moveDay(d,1));return `<button class="day-box ${d===chosenDay?'selected':''} ${d===nowKey()?'today':''}" data-action="select-date" data-date="${d}" type="button"><span class="day-name">${WEEKDAYS_SHORT[i]}</span><strong>${parseDate(d).getDate()}</strong><span class="day-amt">${sec>=60?`${Math.round(sec/60)} dk`:'—'}</span></button>`;}).join('')}</div><div class="gap-20"></div><div class="inline-row"><span class="tag">Bu hafta: ${hrLabel(week.seconds)} / ${hrLabel(week.goal)} saat</span><button class="text-action" type="button" data-action="go-home">Günlük görevlere git →</button></div></section>
 <section class="card">${sectionHead('Haftalık Okul ve Etüt Programı','Buradaki saatler kaydedilmiş çalışma süresi değildir.',`<button class="button small secondary" data-action="open-schedule" type="button">＋ Ders saati ekle</button>`)}<div class="schedule-grid">${DAY_NAMES.map((name,i)=>`<div class="schedule-day"><div class="schedule-label">${name}</div><div class="schedule-items">${state.schedule.filter(s=>s.day===i).sort((a,b)=>a.start.localeCompare(b.start)).map(scheduleItem).join('')||'<span class="hint">Henüz program girilmedi.</span>'}</div></div>`).join('')}</div></section></div>
 <div class="stack"><section class="card">${sectionHead('Seçili Günün Görevleri',fmt.format(parseDate(chosenDay)))}<form id="addTaskForm" class="task-form"><input class="field" maxlength="450" name="taskText" placeholder="Yeni görev..." aria-label="Görev adı" required><select class="field" name="taskCourse" style="width:128px" aria-label="İlgili ders">${coursesOptions('',true)}</select><button class="button primary" type="submit">＋</button></form>${taskList(chosenDay)}</section><section class="card">${sectionHead('Haftalık Ders Hedefleri','Ders bazında hedef / gerçekleşen')}${courseBars(week.start,week.end)}</section><div class="notice"><strong>İpucu:</strong> Haftalık ders ağırlıklarını ve alışkanlıkları <button type="button" class="text-action" data-action="go-settings">Ayarlar</button> bölümünden değiştirebilirsin.</div></div></div>`;}
function renderStats(){const w=weekStats(chosenDay);let max=0;const daily=Array.from({length:7},(_,i)=>{let d=moveDay(w.start,i),s=sumSec(d,moveDay(d,1));max=Math.max(max,s);return {day:d,seconds:s};});const mStart=moveDay(chosenDay,-27);const history=Array.from({length:28},(_,i)=>{const d=moveDay(mStart,i);return {d,seconds:sumSec(d,moveDay(d,1))};});const lastMonthTotal=history.reduce((n,s)=>n+s.seconds,0);const tasks=state.tasks.filter(t=>within(t.due,w.start,w.end));const checked=tasks.filter(t=>t.done).length;return `${pageIntro('VERİLER & ANALİZ','İlerlemeni keşfet.','Çalışma düzenini incele ve haftanın temposunu gör.',true)}
 <div class="metric-grid"><div class="metric-card"><div class="metric-top">Haftalık Çalışma <span class="metric-icon">◷</span></div><span class="metric-value">${hrLabel(w.seconds)}</span><span class="metric-suffix">sa</span><div class="metric-help">Hedef: ${hrLabel(w.goal)} sa · %${pct(w.seconds,w.goal)}</div></div><div class="metric-card"><div class="metric-top">Son 28 Gün <span class="metric-icon">▤</span></div><span class="metric-value">${hrLabel(lastMonthTotal)}</span><span class="metric-suffix">sa</span><div class="metric-help">Gerçek çalışma süresi</div></div><div class="metric-card"><div class="metric-top">Odak Oturumları <span class="metric-icon">✧</span></div><span class="metric-value">${w.sessions}</span><div class="metric-help">Seçili hafta toplamı</div></div><div class="metric-card"><div class="metric-top">Bitirilen Görevler <span class="metric-icon">✓</span></div><span class="metric-value">${checked}</span><span class="metric-suffix">/ ${tasks.length}</span><div class="metric-help">Seçili haftadaki görevler</div></div></div>
 <div class="columns"><div class="stack"><section class="card">${sectionHead('Günlük Çalışma Grafiği','Seçili haftanın 7 günü')}<div class="chart" role="img" aria-label="Günlere göre çalışma süresi: ${daily.map(x=>`${fmt.format(parseDate(x.day))} ${Math.round(x.seconds/60)} dakika`).join(', ')}">${daily.map((x,i)=>`<div class="chart-day"><span class="chart-value">${x.seconds?`${Math.round(x.seconds/60)} dk`:'—'}</span><div class="chart-col" style="height:${max?Math.max(3,Math.round(x.seconds/max*100)):3}%"></div><small>${WEEKDAYS_SHORT[i]}</small></div>`).join('')}</div></section>
 <section class="card">${sectionHead('Son 28 Günün Aktivitesi','Renk koyulaştıkça çalışma süresi artar.')}<div class="month-dots">${history.map(s=>`<div class="dot ${s.seconds===0?'':s.seconds<1800?'level-1':s.seconds<5400?'level-2':'level-3'}" title="${s.d} · ${Math.round(s.seconds/60)} dk" aria-label="${s.d} günü ${Math.round(s.seconds/60)} dakika"></div>`).join('')}</div><div class="gap-14"></div><p class="section-detail">${fmt.format(parseDate(mStart))} – ${fmt.format(parseDate(chosenDay))}</p></section></div><div class="stack"><section class="card">${sectionHead('Derslere Göre Dağılım','Seçili hafta')}${courseBars(w.start,w.end)}</section><section class="card">${sectionHead('Nasıl Hesaplanıyor?')}<div class="help-row"><div class="hint-card"><strong>Çalışma süresi</strong><p>Başlatılan ve kaydedilen odak oturumları ile manuel çalışma kayıtları toplanır.</p></div><div class="hint-card"><strong>Görev ve alışkanlık</strong><p>İşaretleme yapınca süre eklenmez; tamamlanma ayrı hesaplanır.</p></div></div></section></div></div>`;}
function renderSettings(){const total=state.courses.reduce((s,c)=>s+c.weeklyGoal,0);return `${pageIntro('KİŞİSELLEŞTİRME','Her şey senin düzenine göre.','Dersleri, alışkanlıkları ve verilerini buradan yönet.')}
 <div class="columns"><div class="stack"><section class="card">${sectionHead('Dersler ve Haftalık Hedefler',`Toplam: ${minLabel(total)} · Değerler gerçek çalışma hedefidir.`)}<div class="notice warn">Başlangıçta üç doğrulanmış ders hedefi vardır. Kalan <strong>6,5 saat</strong> “Diğer dersler” olarak bırakıldı. Ekran görüntülerindeki diğer dersleri buradan ayrı ayrı ekleyip ağırlıkları değiştirebilirsin.</div><div class="gap-14"></div>${state.courses.map(c=>`<form class="settings-row" data-form="edit-course" data-id="${esc(c.id)}"><i class="course-dot" style="background:${c.color}"></i><div class="content"><label class="field-label">Ders adı</label><input class="field" name="name" maxlength="75" value="${esc(c.name)}" required></div><div class="controls"><label><span class="field-label">Saat/hafta</span><input class="field" type="number" name="hours" min="0" max="100" step="0.25" value="${c.weeklyGoal/60}" required></label><button class="button secondary small" type="submit" title="Kaydet">Kaydet</button><button class="mini-remove" type="button" data-action="remove-course" data-id="${esc(c.id)}" title="Dersi sil">×</button></div></form>`).join('')}<div class="divider"></div><form id="addCourseForm"><label class="field-label">Yeni ders ekle</label><div class="form-row"><input class="field" name="name" maxlength="75" placeholder="Ders adı" required><input class="field" name="hours" aria-label="Haftalık saat hedefi" title="Haftalık hedef (saat)" style="max-width:95px" type="number" step="0.25" min="0" max="100" value="1" required><button class="button primary" type="submit">＋ Ekle</button></div></form></section>
 <section class="card">${sectionHead('Güvenli Veri Yedeği','Kayıtlar yalnızca bu tarayıcıda saklanır.')}<div class="inline-row"><button class="button primary" type="button" data-action="export-data">↓ Yedek indir (.json)</button><button class="button secondary" type="button" data-action="import-data">↑ Yedek geri yükle</button></div><div class="gap-14"></div><div class="notice">Telefon değiştirirken veya tarayıcı verilerini silmeden önce <strong>yedek al</strong>. GitHub Pages, tarayıcıdaki kişisel kayıtlarını başka cihazlarla otomatik senkronize etmez.</div><div class="gap-14"></div><button class="button danger small" type="button" data-action="reset-data">Tüm verileri sıfırla</button></section></div>
 <div class="stack"><section class="card">${sectionHead('Günlük Alışkanlıklar','Alışkanlık listeni istediğin gibi düzenle.')}${state.habits.map(h=>`<form class="settings-row" data-form="edit-habit" data-id="${esc(h.id)}"><span class="habit-emoji">${esc(h.emoji)}</span><div class="content"><input class="field" name="name" value="${esc(h.name)}" maxlength="85" required></div><div class="controls"><button class="button secondary small" type="submit">Kaydet</button><button type="button" class="mini-remove" title="Alışkanlığı sil" data-action="remove-habit" data-id="${esc(h.id)}">×</button></div></form>`).join('')}<div class="divider"></div><form id="addHabitForm"><label class="field-label">Yeni alışkanlık ekle</label><div class="form-row"><input class="field" maxlength="8" name="emoji" style="max-width:58px" aria-label="Emoji" placeholder="✅" value="✅"><input class="field" maxlength="85" name="name" placeholder="Örn. 20 dakika oku" required><button class="button primary" type="submit">＋</button></div></form></section><section class="card">${sectionHead('Uygulama Hakkında')}<p class="subtle">Üyelik veya sunucu bağlantısı gerekmez. Ders listesi, görevler, alışkanlıklar, notlar ve kaydedilmiş oturumlar cihazında tutulur. GitHub Pages üzerinden HTTPS ile açıldığında çevrimdışı çalışma ve ana ekrana yükleme desteği sunulur.</p><div class="gap-14"></div><span class="tag">PWA sürüm 1.0 · Veri şeması v3</span></section></div></div>`;}
function setTab(next){if(!['anasayfa','plan','istatistik','ayarlar'].includes(next))return;tab=next;location.hash=next;render();window.scrollTo({top:0,behavior:'auto'});}
function render(){const node=$('#view');node.innerHTML=tab==='plan'?renderPlan():tab==='istatistik'?renderStats():tab==='ayarlar'?renderSettings():renderHome();document.querySelectorAll('[data-tab]').forEach(b=>{let active=b.dataset.tab===tab;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false');});updateTimer();}
function updateTimer(){const tv=$('#runningTimer');if(tv)tv.textContent=prettyTime(timerElapsed());const mode=$('#timerMode');if(mode)mode.textContent=state.timer.running?'Şu anda çalışıyorsun':'Hazır olduğunda başlat';}
function openModal(title,body){$('#modalTitle').textContent=title;$('#modalContent').innerHTML=body;$('#modal').hidden=false;$('#modal').querySelector('input,select,button')?.focus();}
function closeModal(){$('#modal').hidden=true;$('#modalContent').innerHTML='';}
function startTimer(){if(state.timer.running)return;if(!courseFor(state.timer.courseId)){toast('Önce ders ekle.');return;}state.timer.startedAt=Date.now();state.timer.running=true;save();render();}
function pauseTimer(){if(!state.timer.running)return;state.timer.elapsedSec=timerElapsed();state.timer.startedAt=null;state.timer.running=false;save();render();}
function finishTimer(){const seconds=timerElapsed();if(seconds<1){toast('Henüz kaydedilecek süre yok.');return;}if(!courseFor(state.timer.courseId)){toast('Önce ders seç.');return;}state.sessions.push({id:id(),courseId:state.timer.courseId,seconds,at:new Date().toISOString()});state.timer.elapsedSec=0;state.timer.running=false;state.timer.startedAt=null;save();toast(`${Math.round(seconds/60)} dakika çalışma kaydedildi.`);render();}
function dayChanged(next){if(!/^\d{4}-\d{2}-\d{2}$/.test(next))return;chosenDay=next;render();}
function addTask(form){const text=form.elements.taskText.value.trim().slice(0,450);if(!text)return;const courseId=form.elements.taskCourse.value;state.tasks.push({id:id(),text,due:chosenDay,courseId:courseFor(courseId)?courseId:'',done:false});save();render();}
function applyAction(action,b){const itemId=b.dataset.id;
 switch(action){
 case 'prev-day':dayChanged(moveDay(chosenDay,-1));break;
 case 'next-day':dayChanged(moveDay(chosenDay,1));break;
 case 'select-date':dayChanged(b.dataset.date);break;
 case 'go-home':setTab('anasayfa');break;case 'go-plan':setTab('plan');break;case 'go-stats':setTab('istatistik');break;case 'go-settings':setTab('ayarlar');break;
 case 'delete-task':state.tasks=state.tasks.filter(t=>t.id!==itemId);save();render();break;
 case 'toggle-habit':{let checks=state.habitChecks[chosenDay]||[];state.habitChecks[chosenDay]=checks.includes(itemId)?checks.filter(x=>x!==itemId):[...checks,itemId];save();render();break;}
 case 'start-timer':startTimer();break;case 'pause-timer':pauseTimer();break;case 'finish-timer':finishTimer();break;
 case 'open-manual':openModal('Çalışma Süresi Ekle',`<form id="manualForm" class="modal-form"><div><label class="field-label" for="manualCourse">Ders</label><select id="manualCourse" name="course" class="field" required>${coursesOptions(state.timer.courseId)}</select></div><div class="form-row"><div class="flex-1"><label class="field-label" for="manualMinutes">Çalışma süresi (dakika)</label><input id="manualMinutes" class="field" name="minutes" type="number" min="1" max="1440" step="1" value="30" required></div><div class="flex-1"><label class="field-label" for="manualDate">Tarih</label><input id="manualDate" class="field" name="date" type="date" value="${chosenDay}" required></div></div><p class="hint">Seçilen güne ve derse gerçek çalışma süresi ekler. Tekrar kaydetmemeye dikkat et.</p><button class="button primary full" type="submit">Süreyi kaydet</button></form>`);break;
 case 'open-schedule':openModal('Programa Ders / Etüt Ekle',`<form id="scheduleForm" class="modal-form"><div><label class="field-label">Ad</label><input class="field" name="title" maxlength="110" required placeholder="Örn. Termodinamik - Amfi 2"></div><div><label class="field-label">Haftanın günü</label><select name="day" class="field">${DAY_NAMES.map((name,i)=>`<option value="${i}" ${i===(parseDate(chosenDay).getDay()+6)%7?'selected':''}>${name}</option>`).join('')}</select></div><div class="form-row"><div class="flex-1"><label class="field-label">Başlangıç</label><input class="field" name="start" type="time" value="09:00" required></div><div class="flex-1"><label class="field-label">Bitiş</label><input class="field" name="end" type="time" value="10:00" required></div></div><div><label class="field-label">Etkinlik türü</label><select class="field" name="kind"><option value="class">Okul / sınıf dersi (hedefe sayılmaz)</option><option value="study">Planlanan etüt (tamamlanınca sayaçta kaydet)</option></select></div><button class="button primary full" type="submit">Programa ekle</button></form>`);break;
 case 'delete-schedule':state.schedule=state.schedule.filter(s=>s.id!==itemId);save();render();break;
 case 'remove-course':{if(state.courses.length<=1){toast('En az bir ders bulunmalı.');break;}const c=courseFor(itemId);if(!c)break;const cnt=state.sessions.filter(s=>s.courseId===itemId).length;if(!confirm(`“${c.name}” dersini silmek istiyor musun? ${cnt} çalışma kaydı da silinecek.`))break;state.courses=state.courses.filter(c=>c.id!==itemId);state.sessions=state.sessions.filter(s=>s.courseId!==itemId);state.tasks.forEach(t=>{if(t.courseId===itemId)t.courseId='';});if(state.timer.courseId===itemId){state.timer={courseId:state.courses[0].id,elapsedSec:0,running:false,startedAt:null};}save();render();break;}
 case 'remove-habit':{const h=state.habits.find(h=>h.id===itemId);if(!h||!confirm(`“${h.name}” alışkanlığını silmek istiyor musun?`))break;state.habits=state.habits.filter(h=>h.id!==itemId);for(const d in state.habitChecks)state.habitChecks[d]=state.habitChecks[d].filter(x=>x!==itemId);save();render();break;}
 case 'export-data':exportData();break;
 case 'import-data':$('#importFile').click();break;
 case 'reset-data':if(confirm('TÜM kayıtları, dersleri, görevleri ve alışkanlıkları sıfırlamak istediğinden emin misin? Önce yedek almak iyi bir fikirdir.')){if(confirm('Son onay: Tüm yerel veriler silinsin mi?')){state=defaults();chosenDay=nowKey();save();render();toast('Veriler sıfırlandı.');}}break;
 }
}
function exportData(){try{const blob=new Blob([JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`ders-rutin-yedek-${nowKey()}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Yedek dosyan hazır.');}catch(e){toast('Yedek oluşturulamadı.');}}
async function importData(file){if(!file)return;if(file.size>4*1024*1024){toast('Yedek dosyası çok büyük (en fazla 4 MB).');return;}try{const raw=JSON.parse(await file.text());if(!raw||!Array.isArray(raw.courses)||!Array.isArray(raw.sessions)||!Array.isArray(raw.tasks)||!Array.isArray(raw.habits))throw Error('format');if(!confirm('Yedek geri yüklendiğinde bu cihazdaki mevcut kayıtlar değiştirilecek. Devam edilsin mi?'))return;state=cleanData(raw);save();render();toast('Yedek geri yüklendi.');}catch(e){toast('Geçerli bir Ders & Rutin yedeği seç.');}finally{$('#importFile').value='';}}
function handleSubmit(e){const form=e.target;if(!(form instanceof HTMLFormElement))return;e.preventDefault();if(form.id==='addTaskForm')addTask(form);
 else if(form.id==='addCourseForm'){let name=form.elements.name.value.trim(),hours=Number(form.elements.hours.value);if(!name||!Number.isFinite(hours)||hours<0||hours>100)return;state.courses.push({id:id(),name:name.slice(0,75),weeklyGoal:Math.round(hours*60),color:COLORS[state.courses.length%COLORS.length]});save();render();toast('Ders eklendi.');}
 else if(form.dataset.form==='edit-course'){const c=courseFor(form.dataset.id);if(!c)return;let name=form.elements.name.value.trim(),hours=Number(form.elements.hours.value);if(!name||!Number.isFinite(hours)||hours<0||hours>100){toast('Geçerli bir ders adı ve saat gir.');return;}c.name=name.slice(0,75);c.weeklyGoal=Math.round(hours*60);save();render();toast('Ders hedefi güncellendi.');}
 else if(form.id==='addHabitForm'){let name=form.elements.name.value.trim();if(!name)return;state.habits.push({id:id(),name:name.slice(0,85),emoji:form.elements.emoji.value.slice(0,8)||'✅'});save();render();toast('Alışkanlık eklendi.');}
 else if(form.dataset.form==='edit-habit'){let h=state.habits.find(h=>h.id===form.dataset.id);if(!h)return;const name=form.elements.name.value.trim();if(!name)return;h.name=name.slice(0,85);save();render();toast('Alışkanlık güncellendi.');}
 else if(form.id==='manualForm'){const courseId=form.elements.course.value,mins=Number(form.elements.minutes.value),day=form.elements.date.value;if(!courseFor(courseId)||!Number.isInteger(mins)||mins<1||mins>1440||!/^\d{4}-\d{2}-\d{2}$/.test(day)){toast('Bilgileri kontrol et.');return;}state.sessions.push({id:id(),courseId,seconds:mins*60,at:new Date(`${day}T12:00:00`).toISOString()});save();closeModal();render();toast(`${mins} dakika çalışma eklendi.`);}
 else if(form.id==='scheduleForm'){const name=form.elements.title.value.trim(),day=Number(form.elements.day.value),start=form.elements.start.value,end=form.elements.end.value,kind=form.elements.kind.value;if(!name||day<0||day>6||start>=end){toast('Başlangıç bitişten önce olmalı.');return;}state.schedule.push({id:id(),title:name.slice(0,110),day,start,end,kind:kind==='study'?'study':'class'});save();closeModal();render();toast('Haftalık programa eklendi.');}
}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-tab]');if(btn){setTab(btn.dataset.tab);return;}const action=e.target.closest('[data-action]');if(action){applyAction(action.dataset.action,action);return;}});
document.addEventListener('submit',handleSubmit);
document.addEventListener('change',e=>{const el=e.target;if(el.id==='chosenDate'){dayChanged(el.value);return;}if(el.id==='timerCourse'){state.timer.courseId=el.value;save();return;}if(el.dataset.taskCheck){const t=state.tasks.find(t=>t.id===el.dataset.taskCheck);if(t){t.done=el.checked;save();render();}return;}});
document.addEventListener('input',e=>{if(e.target.id==='dailyNote'){const val=e.target.value,day=chosenDay;clearTimeout(noteSaveTimeout);const status=$('#noteStatus');if(status)status.textContent='Kaydediliyor...';noteSaveTimeout=setTimeout(()=>{state.notes[day]=val;save();const n=$('#noteStatus');if(n&&chosenDay===day)n.textContent='✓ Kaydedildi.';},250);}});
$('#goToday').addEventListener('click',()=>{chosenDay=nowKey();setTab('anasayfa');});
$('#closeModal').addEventListener('click',closeModal);
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
$('#importFile').addEventListener('change',e=>importData(e.target.files?.[0]));
window.addEventListener('hashchange',()=>{const hash=location.hash.slice(1);if(hash!==tab&&['anasayfa','plan','istatistik','ayarlar'].includes(hash)){tab=hash;render();}});
document.addEventListener('visibilitychange',()=>{if(!document.hidden){updateTimer();if(tab==='anasayfa'&&nowKey()!==chosenDay)render();}});
window.setInterval(updateTimer,1000);
render();save();
if('serviceWorker' in navigator && /^https?:$/.test(location.protocol))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();
